name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:                                   #added
      run-job:
        description: "Run Specific Job"
        type: boolean
        required: false
      custom_message:
        description: "Enter a custom message"
        type: string
        required: true                        #end

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Debugging Environment Variable
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV   # Set debug variable for the job
      - name: Print Debug Message
        run: echo "Debugging is now enabled for the steps in this job."
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:                                       #added
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo ${{ inputs.custom_message }} #end

      - name: Printing run-job boolean value  #added
        if: ${{ inputs.run-job == true }} 
        run: echo ${{ inputs.run-job }}  
